### ISSUE TITLE
Location while Drone camera

### ISSUE THREAD

**Issue by tukorneger** [baumhoto/FSBingMapsConnect#2]
Hi there, is there a way to get the position when in drone camera, instead of the plane location?

I like to flight in drone mode so i let the plane on ground and visit places in drione camera.
Right now, this mod takes the position of the plane, not my actual drone camera one.

Thanks, and by the way, great job. Thank you!

**Comment by baumhoto** [comment]
Hi,

haven't looked at in a while but as far as I can remember there was a lot of data you could get from Flight Simulator via the SimConnect Api. if Drone position is one of them I need to check.

**Comment by tukorneger** [comment]
It would be great if you could check it.
Anyway, i want to give thanks to you for sharing this awesome app!

**Comment by baumhoto** [comment]
unfortunately Drone position is not available. checked [Flight Simulator Aircraft Simulation Variables](https://docs.flightsimulator.com/html/index.htm#t=Programming_Tools%2FSimVars%2FAircraft_Simulation_Variables.htm) where you can find _PLANE LATITUDE_ and _PLANE_LONGITUDE_ which is used to get the Plane Position, but there is nothing for Drone or anything similar.
